### ISSUE TITLE
conditional analysis column name

### ISSUE THREAD

**Issue by jennaccarlson** [UW-GAC/analysis_pipeline#31]
Documentation for the conditional_variant_file says columns should include chromosome (or chr) and variant.id. However, the null model will not run successfully unless columns are chromosome and variant.id (chr does not work).

**Comment by smgogarten** [comment]
Make sure you've installed the most recent version of the TopmedPipeline R package (2.6.0). This was a recent change, so older versions of the package require "chromosome" as a column name.
