### ISSUE TITLE
Error openning

### ISSUE THREAD

**Issue by phuwanat** [UW-GAC/analysis_pipeline#4]
Hello,

I am trying to run the pipeline on my cluster. After I configured to fit with the cluster and the first job (vcf2gds) seems to work, the following jobs (merge_gds, unique_variant_ids, cleanup) failed. Do I need to set specific configuration to correctly located these scripts. The error is the following:

repsa@homburg04 ~/sw/genesis/analysis_pipeline % python2.7 vcf2gds.py testdata/vcf2gds.config --cluster_type UW_Clu                                                                                                  ster
AWS batch not supported.
Submitting job Your job-array 972421 (vcf2gds)
Unable to read script file because of error: error opening job-array: No such file or directory
Submitting job  (merge_gds)
Unable to read script file because of error: error opening unique_variant_ids: No such file or directory
Submitting job  (unique_variant_ids)
Unable to read script file because of error: error opening cleanup: No such file or directory
Submitting job  (cleanup)

Note: The individual gds files were created successfully.

Thanks,
Phuwanat

**Comment by rollinroy** [comment]
Hi Phuwanat,
I would like to know more about your cluster.  Could you provide the
following:

   - A high level summary of the number of nodes; the job scheduler (e.g.,
   sge); etc
   - If you are using sge job scheduler could you provide the following:
      - list of all queues (qconf -shgrpl)
      - configurations (qconf -sconf)
      - complex attributes (qconf -sc)
      - parallel environments (qconf -spl)
      - if you have "local" parallel environment, more details (qconf -sp
      local)

What shell are you using (bash, etc)? and what flavor of linux are you
running? What version of R are you running?

Could you run the vcf2gds pipeline again with the --print options which
prints the commands but does not execute them.  In your case it would be :

 python2.7 vcf2gds.py testdata/vcf2gds.config  --print

​(Before you run this command could you also edit the
.../analysis_pipeline/cluster_cfg.json and change "debug": 0 to "debug": 1)

​Although I don't think your command line is the problem, I would recommend
using the full path with specifying the pipeline script (vcf2gds.py) or at
least using "./".​


​We've used this pipeline on both a red-hat linux (our local cluster) and
ubuntu (on the amazon cloud) so once we have things configured things
should run fairly smoothly.
​
cheers, roy

**Comment by phuwanat** [comment]
Hello Roy,

I successfully re-ran the script while adding my appropriate queue name and passing the current PATH to the cluster. Thank you so much! 

The following is my current working config:
AWS batch not supported.
0>>> Dump of standard cluster cfg ... 

{
   "memory_limits": {}, 
   "parallel_env": "ompi", 
   "submit_cmd": "qsub", 
   "submit_opts": {
      "-N": "", 
      "-S": "/bin/bash", 
      "-cwd": "", 
      "-j": "y", 
      "-l": "lx6", 
      "-terse": "", 
      "-v": "PATH"
   }
}
Submitting job 1005987 (vcf2gds)
Submitting job 1005988 (merge_gds)
Submitting job 1005989 (unique_variant_ids)
Submitting job 1005990 (cleanup)

Phuwanat
