### ISSUE TITLE
Update MAF/missingness filter in pca_corr_vars to work on only the sample set used in PCA

### ISSUE THREAD

**Issue by amstilp** [UW-GAC/analysis_pipeline#41]
Right now, pca_corr_vars filters the GDS to the MAF and missingness thresholds specified using the entire sample, not just the sample set included in PCA. It should be updated to calculate MAF/missingness only on the PCA sample set.

**Comment by amstilp** [comment]
Should MAF/missingness be calculated on the unrelateds, or all unrelateds + relateds in the PCA run?

**Comment by mconomos** [comment]
That is a good question, for which I don't have a definitive answer. But I think I would say all sample in the PCA (so unrelateds + relateds)? I'm happy to hear other opinions on this though.

**Comment by smgogarten** [comment]
I recall having a discussion about this a few years ago, we we decided that MAF calculations should be done on all samples. We didn't talk about missingness specifically, but I think it should be the same.
