### ISSUE TITLE
Included chrX VCF fails due to containing NA in FILTER column.

### ISSUE THREAD

**Issue by aofarrel** [UW-GAC/analysis_pipeline#46]
When WDLizing this pipeline, [I found this issue](https://github.com/aofarrel/analysis_pipeline_WDL/issues/7). When I replicated it in both the CWL version and the raw R scripts, I realized it's not related to WDL. [If we filter the VCF to remove all rows that contain NA for FILTER](https://github.com/aofarrel/analysis_pipeline_WDL/commit/5e0a9fc41c3048487ebcdd286c2e0025975b61f3), then check_gds will complete successfully.

**Comment by aofarrel** [comment]
Link to a filtered chrX that I've been using for testing since: https://github.com/DataBiosphere/analysis_pipeline_WDL/blob/main/testdata/1KG_phase3_subset_chrX.vcf

This filtered chr passes on the CWL and WDL version of this pipeline, and should pass the original pipeline here too.

**Comment by smgogarten** [comment]
I think that file is the same as [this one](https://github.com/DataBiosphere/analysis_pipeline_WDL/blob/main/_test-data-and-truths_/vcfs/alternative_vcfs/1KG_phase3_subset_chrX.vcf)

Fixed in 75feffe
