### ISSUE TITLE
pcrelateMakeGRM is now defunct

### ISSUE THREAD

**Issue by DanielEWeeks** [UW-GAC/analysis_pipeline#7]
The TopmedPipeline R package calls `pcrelateMakeGRM`, but this function is now defunct in the current version of  GENESIS.  It is clear we should adjust the TopmedPipeline to instead call `pcrelateToMatrix`, but our initial attempts to do this failed.  Any advice/suggestions on how to fix this?
Thank you,
Dan

**Comment by smgogarten** [comment]
There are two options:
1) use an older version of GENESIS, such as this one: https://github.com/UW-GAC/GENESIS/releases/tag/v2.13.2
2) Use the [devel branch](https://github.com/UW-GAC/analysis_pipeline/tree/devel) of analysis_pipeline, which has been updated to use the most recent GENESIS. I plan to release a new pipeline version soon.
